# Generated by Django 5.1.3 on 2024-11-13 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('date_of_posted', models.DateField(default=datetime.datetime(2024, 11, 13, 12, 0, 46, 414121, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
