# Generated by Django 5.1.3 on 2024-11-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_activity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
