# Generated by Django 5.1.3 on 2024-11-14 09:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_activity', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_of_posted', models.DateField(default=datetime.datetime(2024, 11, 14, 9, 24, 23, 358944, tzinfo=datetime.timezone.utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_activity.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_activity.book')),
            ],
        ),
    ]
