# Generated by Django 5.1.3 on 2024-11-14 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_activity', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('date_of_creation', models.DateField(default=datetime.datetime(2024, 11, 14, 11, 14, 58, 810712, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='date_of_posted',
            field=models.DateField(default=datetime.datetime(2024, 11, 14, 11, 14, 58, 810712, tzinfo=datetime.timezone.utc)),
        ),
    ]
