# Generated by Django 5.1.3 on 2024-11-14 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_activity', '0004_user_alter_review_date_of_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='review',
            name='date_of_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
