# Generated by Django 5.1.3 on 2024-11-14 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_activity', '0005_delete_user_alter_review_date_of_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('date_of_creation', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
